Added the constraints editor popover
MicrosoftDocs/xamarin-docs pull request #2120
Opened 2019-09-12 11:52 UTC by prashantvc

- Added the initial docs
- Added the screenshots

2019-09-12 18:50 UTC, conceptdev requested changes
Hey, thanks for doing this! Made two small change requests.

2019-09-12 18:50 UTC, conceptdev commented on docs/ios/user-interface/designer/designer-auto-layout.md
> +On opening the constraints popover it displays any preset constraints on the view. We can set all the spacing constraints selecting _All Sides_ from the combobox on top right corner, and select _Clea
Hey, use **bold** for these items rather than italic - we always use **bold** for stuff displayed in the UI (italic is rarely used, it affects readability, especially in some other language scripts).

2019-09-12 18:50 UTC, conceptdev commented on docs/ios/user-interface/designer/designer-auto-layout.md
> +![constraints spacing](images/constraints-spacing.png)
the images should be in the `designer-auto-layout-images` folder, with the other images for this page ;)

2019-09-13 08:50 UTC, prashantvc commented
Fixed review items

2019-09-13 15:09 UTC, conceptdev approved these changes
Perfect!

2019-09-13 15:09 UTC, merged